version: '3.8'

services:
  app:
    build: .
    container_name: backend_app
    ports:
      - "8000:8000"
    volumes:
      # - db_data:/app/data
      - ./data:/app/data
    environment:
      - DATABASE_URL=sqlite:///./data/app.db
      - PYTHONPATH=/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  test:
    build: .
    container_name: backend_test
    # volumes:
      # - .:/app
    environment:
      - PYTHONPATH=/app
    command: pytest app/tests/ -v

# volumes:
#   db_data: